[build]
  # Static site - no build command needed
  command = ""
  # Publish the root directory (contains index.html)
  publish = "."

[build.environment]
  # Disable Next.js detection completely
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

# Redirect requests to extension-card-generator for the main app
[[redirects]]
  from = "/app/*"
  to = "/extension-card-generator/:splat"
  status = 200

# Serve index.html for root requests
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Specific headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for static assets
[[headers]]
  for = "/extension-card-generator/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/extension-card-generator/templates/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
